### ISSUE TITLE
CMake was unable to find a build program corresponding to "MinGW Makefiles"

### ISSUE THREAD

**Issue by TAMARIW** [risherlock/FloatSat#2]
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
make: *** [rodos] Fehler 1

**Comment by risherlock** [comment]
Please install MinGW: https://sourceforge.net/projects/mingw/

**Comment by TAMARIW** [comment]
It works now Thank you very much
